spring:
  application:
    name: MedicineAssistantSystem
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB
  ai:
    model:
      chat: dashscope
    dashscope:
      api-key: your-api-key
      chat:
        options:
          model: qwen-plus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/MedicineAssistantSystem?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  storage:
    root: ${user.dir}/medicine-uploads
  mp-monitor:
    base-url: https://www.dajiala.com/fbmain/monitor/v3/post_history
    key: your-api-key
    default-name: 中药新药
siliconflow:
  voice-key: your-api-key
  voice-model: FunAudioLLM/CosyVoice2-0.5B