spring:
  application:
    name: MedicineAssistantSystem
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB
  ai:
    ollama:
      base-url: http://10.20.62.52:11434
      chat:
        model: qwen3.5:35b
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/MedicineAssistantSystem?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 556JKAD@#79632bbc
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  storage:
    root: ${user.dir}/medicine-uploads